### ISSUE TITLE
1.0.0 Master Checklist

### ISSUE THREAD

**Issue by brandonLi8** [brandonLi8/sim-core#1]
# Top-level Checklist to be completed for 1.0.0:

## Design
- [x] [Design Document](https://docs.google.com/document/d/137mAD1gZpnaGwOpMoRLifsAzJuODE5cTAQLjnj29zjM/edit) Created (Date: //10/28/2019)

## Implementation
- [x] Repository created (Date: //10/29/2019)
- [ ] License added (Date: //)
- [x] [Grunt Config](https://github.com/brandonLi8/grunt-config) Added
- [x] Github Project Roadmap completed (Date: //10/31/2019)
- [ ] Code Reviewer Identified and Completed (Date: //)
- [ ] Verify Credits (Date: //)
- [ ] domain/cname confirmed (Date: //)
- [ ] Published! (Date: //)

## Grunt Config
- [x] `npm` initiated with `package.json` (Date: //10/31/2019)
- [x] GitHub labels added (Date: //10/31/2019)
- [x] `.gitignore` generated (Date: //10/31/2019)
- [ ] `travis.yml` created (Date: //)

## Testing
- [ ] Performance acceptable (Date: //)
- [ ] Feature Complete (Date: //)
